### ISSUE TITLE
Missing parentheses in call to 'print' File "./keyboards/anne_pro/dfuse-pack.py", line 143

### ISSUE THREAD

**Issue by maowohl** [msvisser/qmk_firmware#10]
I tried to run the command 

`./keyboards/anne_pro/dfuse-pack.py -b 0x08004000:anne_pro_default.bin anne_pro_default.dfu`

as shown in the README.md but got the following message:

> $ ./keyboards/anne_pro/dfuse-pack.py -b 0x08004000:anne_pro_default.bin anne_pro_default.dfu
  File "./keyboards/anne_pro/dfuse-pack.py", line 143
    print "Address %s invalid." % address
                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Address %s invalid." % address)?

Changing
`print "Address %s invalid." % address`
to
`print("Address %s invalid." % address)`
on the file appears to fix it

**Comment by msvisser** [comment]
Hi, my apologies for the late response.

The `dfuse-pack.py` script I copied from another project, mostly for people on Windows to try this firmware with the default upload tool. However it is not the preferred method for uploading firmware to your keyboard, instead you should probably use the make command as outlined in the README.

If you would like to incorporate the fix in this repo, please submit a pull request, and I will gladly merge it!
