### ISSUE TITLE
Space Cadet not working properly

### ISSUE THREAD

**Issue by diegolhambi** [msvisser/qmk_firmware#11]
I tried to use the Space Cadet Shift but only sometimes when I tap the SHIFT it sends the parentheses.

The `KC_GESC` and `LT(layer, mod)` work fine.
I think these features the share same functionalities involving time.

**Comment by diegolhambi** [comment]
I configured the `CH_CFG_ST_FREQUENCY` to `1000` and now the space cadet is working fine and even the tap dance is working (in the past i was not able to get working properly).

**Comment by ClaireSoftware** [comment]
Talked to someone in the QMK discord about this, they said:
"not really a fix unfortuntely
that causes other issues, like LT to not trigger properly, IIRC
and that's for ARM
I think the Anne Pro is AVR"

**Comment by msvisser** [comment]
The configuration for those values was taken from the Blue Pill example of QMK, so I never really thought about them. Although looking through the QMK repository most keyboards seem to use either `1000`, `10000` or `100000`. If you would test out these values and create a pull request I would happily merge it

**Comment by msvisser** [comment]
This should be fixed by #12, if not please leave another comment!
