### ISSUE TITLE
Wrong Alt key mapped on Anne Pro 2 Windows Layout

### ISSUE THREAD

**Issue by mdbovo** [msvisser/qmk_firmware#13]
Both alts are mapped as KC_LALT so it's not possible to produce keys like ñ (ALT+n). The correct layout (tested) is:

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT(
      KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS, KC_EQL,  KC_BSPC,
      KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_LBRC, KC_RBRC, KC_BSLS,
      KC_CAPS, KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,          KC_ENT,
      KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH,           MT(MOD_RSFT, KC_UP),
      KC_LCTL, KC_LGUI, KC_LALT,                   KC_SPACE,                  KC_RALT, LT(1,KC_LEFT), LT(2,KC_DOWN), MT(MOD_RCTL, KC_RGHT)
  ),

**Comment by msvisser** [comment]
This should be fixed now
