### ISSUE TITLE
bluetooth problem 

### ISSUE THREAD

**Issue by ghost** [msvisser/qmk_firmware#14]
keyboard freezes (led works, no respone for any input, only back reset button helps) while connected to BT, i can connect only with legacy BT, if you try to connect with standart BT it freezes when it ask for the bt code. with usb it works fine

bt worked fine until (not 100% sure but it could be that) [this commit](https://github.com/msvisser/qmk_firmware/commit/2dde284d1738c451f98505d6b961dbf3858e224a#diff-47b706e9b8ba127c097d99f340005287)

**Comment by msvisser** [comment]
It seems you have indeed found a bug and pinpointed the correct commit. I am not quite sure why this commit would break the Bluetooth pairing but I will revert the commit shortly. This should at least fix Bluetooth to be usable again, but I will have to find a different solution for getting macros working over Bluetooth.
