### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by demersn** [msvisser/qmk_firmware#16]
I'm trying to get QMK on my Anne Pro 1 and getting stuck at the `apply_patch.sh` stage. My build env. seems to be working, as I'm able to build other keyboards. It's my first time using QMK.

## Describe the Bug
When running `apply_patch.sh` , I get the following error:
```
demer_000@Nicolas MINGW64 /d/qmk/qmk_firmware
$ ./keyboards/anne_pro/apply_patch.sh
error: le patch a échoué : os/hal/ports/STM32/STM32L1xx/platform.mk:17
error: os/hal/ports/STM32/STM32L1xx/platform.mk : le patch ne s'applique pas
```
Sorry for the french commands, basically it says: match failed, and patch doesn't apply.

## System Information

 - Keyboard:  Anne Pro 1
 - Operating system: Windows 10, msys2 64
 - AVR GCC version: 8.3.0

 - ARM GCC version: `arm-none-eabi-gcc.exe (GNU Tools for Arm Embedded Processors 8-2019-q3-update) 8.3.1 20190703 (release) [gcc-8-branch revision 273027]`

 - QMK Firmware version: 0.8.106

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

Thanks

**Comment by srobies** [comment]
I had the same issue, but then I discovered you don't technically need the patch to build the firmware. Use `CFLAGS="-Wno-error=deprecated" make anne_pro:KEYMAP:dfu-util` where "KEYMAP" is the folder containing the files you want to use to build the firmware. I haven't had any issues so far using this.

**Comment by msvisser** [comment]
@demersn I'm unable to reproduce the problem. When I pull a clean version of the repository I can correctly build it following the steps as described in the README for the keyboard.

@LrobieProject this seems to be a problem with the newer compiler versions, you solutions seems to work for me. As far as I know you will still need the patch.

**Comment by msvisser** [comment]
Alright, all of these problems should be solved in the latest version. I have updated to the most recent version of QMK which also updated ChibiOS, which means the patch is no longer needed and the deprecated errors are gone.
