### ISSUE TITLE
[Feature request] Keyboard idling

### ISSUE THREAD

**Issue by ghost** [msvisser/qmk_firmware#3]
Force backlight to turn off when kb are idling for 30 minutes (example) on USB mode and for 3 minutes on Bluetooth mode. If user taps any key - backlight turns on.

**Comment by msvisser** [comment]
This is a great idea! I have been thinking about this myself.
I will have to look into whether QMK supports this type of idling or if we would have to implement it ourselves. If you find such a feature in QMK please let me know, otherwise I will look at implementing it myself.

**Comment by ghost** [comment]
I'm not sure exactly but maybe [that's it](https://docs.qmk.fm/#/custom_quantum_functions?id=keyboard-idlingwake-code).

**Comment by msvisser** [comment]
I have looked at those before, unfortunately it does not work as expected. The suspend is only ever activated if the computer suspends the USB connection with the keyboard.

So I think we need to have a look at doing it ourselves, which should not be too hard to do.

**Comment by ghost** [comment]
Well alright. I think you also should look at suspending after pc shutdown and waking backlight up when pc detects the keyboard on uefi/bios launch state (example).

Also it was implemented in obins 0.13 rom, but it works broken.

**Comment by msvisser** [comment]
I have added some basic support for keyboard idling, currently there is no difference for Bluetooth or USB, however it does turn off the lighting after a set amount of seconds.
