### ISSUE TITLE
Battery operation issues

### ISSUE THREAD

**Issue by jesusvallejo** [msvisser/qmk_firmware#6]
When battery is plugged, if usb is detached before conecting to bluetooth, kb becomes unresponsive, even its impossible to turn off the lights.

**Comment by msvisser** [comment]
I have had this issue before, however I thought it was fixed in https://github.com/msvisser/qmk_firmware/commit/68ea4902c32684c15a7aaf9ca77b8af0b9a57c97. If you are not up to date, please check this first, otherwise let me know if you have a way to reproduce it.

**Comment by jesusvallejo** [comment]
Correct, i was some commits behind, i've been trying it for a while and it works perfect.
